language: java
jdk:
  - oraclejdk8

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - git clone -b travis `git config --get remote.origin.url` target/travis
  - echo $FOO | gpg --passphrase-fd 0 target/travis/secret.key.gpg
  - echo $FOO | gpg --passphrase-fd 0 target/travis/public.key.gpg
  - gpg --import target/travis/public.key
  - gpg --allow-secret-key-import --import target/travis/secret.key

script: mvn deploy --settings target/travis/settings.xml

env:
  global:
  - secure: JeowOrSTifk1RCFjnV/wTWtNBlRZ1sX2W/7h4FUE60OXrvWoBrfjD9/B6/QfZYAk7yO9yAPdBj0L2du5PoXiK2y7pqGClUAOoZBxoVQyNYl7V/dydUXrRXG5hl+oNTWeTWIfIpdLX4yXzBYAhrwMQ7R4zfQrEzaB63/IvWMTg/c=
  - secure: Prko9/ozCM4FoMlRAqfIXkQ1UdZUkgRqA5WSaljkbQhQGn9kKiVTl3Hm3UCrjUJknE1cYfLYjpI54b5nPZEOc+3O7UfSZ8SYRUAX+APIhBHUhDL/U2Ar95If/Myqc9uI43Ket22al4HLryUmSLBB3uKtiElsS69VrFRMdCHDcno=
  - secure: J1S2mYzgTXwv1u+pEXyiQ7p5YB/pvEIp+vohFHR5WjB/vxWz8uepHnUC3bBpZc/lpdADd2kYx43HT24hVcaw4Sve0upoIhrcj+tjQoHOkDE8tTq9xdJcFuwyLA+PgAFJmhJ+FCJyuvSJAUQlFDXHzMHbRiP6/GGPtyUz3Ub1xx0=
